2024-09-10 13:45:45.560 [info] Experiment 'pythonaacf' is active
2024-09-10 13:45:45.563 [info] Experiment 'pythonRecommendTensorboardExt' is active
2024-09-10 13:45:45.563 [info] Experiment 'pythonTerminalEnvVarActivation' is active
2024-09-10 13:45:45.563 [info] Experiment 'pythonTestAdapter' is active
2024-09-10 13:45:45.563 [warning] Dir "/home/ec2-user/.pixi/envs" is not watchable (directory does not exist)
2024-09-10 13:45:45.563 [info] Default formatter is set to null for workspace /home/ec2-user
2024-09-10 13:45:45.563 [info] Starting Environment refresh
2024-09-10 13:45:45.564 [info] > pixi --version
2024-09-10 13:45:45.564 [info] > hatch env show --json
2024-09-10 13:45:45.566 [info] cwd: .
2024-09-10 13:45:45.618 [info] > C:\Users\danie\AppData\Local\Microsoft\WindowsApps\python3.11.exe -I ./.vscode-server/extensions/ms-python.python-2024.14.0-linux-x64/python_files/get_output_via_markers.py ./.vscode-server/extensions/ms-python.python-2024.14.0-linux-x64/python_files/interpreterInfo.py
2024-09-10 13:45:45.618 [info] Environments refresh paths discovered: 1397 milliseconds
2024-09-10 13:45:45.661 [error] [Error: Command failed: C:\Users\danie\AppData\Local\Microsoft\WindowsApps\python3.11.exe -I /home/ec2-user/.vscode-server/extensions/ms-python.python-2024.14.0-linux-x64/python_files/get_output_via_markers.py /home/ec2-user/.vscode-server/extensions/ms-python.python-2024.14.0-linux-x64/python_files/interpreterInfo.py
/bin/sh: line 1: C:UsersdanieAppDataLocalMicrosoftWindowsAppspython3.11.exe: command not found

	at genericNodeError (node:internal/errors:984:15)
	at wrappedFn (node:internal/errors:538:14)
	at ChildProcess.exithandler (node:child_process:422:12)
	at ChildProcess.emit (node:events:531:35)
	at maybeClose (node:internal/child_process:1105:16)
	at ChildProcess._handle.onexit (node:internal/child_process:305:5)] {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'C:\\Users\\danie\\AppData\\Local\\Microsoft\\WindowsApps\\python3.11.exe -I /home/ec2-user/.vscode-server/extensions/ms-python.python-2024.14.0-linux-x64/python_files/get_output_via_markers.py /home/ec2-user/.vscode-server/extensions/ms-python.python-2024.14.0-linux-x64/python_files/interpreterInfo.py'
}
2024-09-10 13:45:45.717 [info] Starting Environment refresh
2024-09-10 13:45:45.742 [info] Environments refresh paths discovered: 26 milliseconds
2024-09-10 13:45:48.376 [info] > C:\Users\danie\AppData\Local\Microsoft\WindowsApps\python3.11.exe -I ./.vscode-server/extensions/ms-python.python-2024.14.0-linux-x64/python_files/get_output_via_markers.py ./.vscode-server/extensions/ms-python.python-2024.14.0-linux-x64/python_files/interpreterInfo.py
2024-09-10 13:45:49.056 [error] [Error: Command failed: C:\Users\danie\AppData\Local\Microsoft\WindowsApps\python3.11.exe -I /home/ec2-user/.vscode-server/extensions/ms-python.python-2024.14.0-linux-x64/python_files/get_output_via_markers.py /home/ec2-user/.vscode-server/extensions/ms-python.python-2024.14.0-linux-x64/python_files/interpreterInfo.py
/bin/sh: line 1: C:UsersdanieAppDataLocalMicrosoftWindowsAppspython3.11.exe: command not found

	at genericNodeError (node:internal/errors:984:15)
	at wrappedFn (node:internal/errors:538:14)
	at ChildProcess.exithandler (node:child_process:422:12)
	at ChildProcess.emit (node:events:531:35)
	at maybeClose (node:internal/child_process:1105:16)
	at Socket.<anonymous> (node:internal/child_process:457:11)
	at Socket.emit (node:events:519:28)
	at Pipe.<anonymous> (node:net:338:12)] {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'C:\\Users\\danie\\AppData\\Local\\Microsoft\\WindowsApps\\python3.11.exe -I /home/ec2-user/.vscode-server/extensions/ms-python.python-2024.14.0-linux-x64/python_files/get_output_via_markers.py /home/ec2-user/.vscode-server/extensions/ms-python.python-2024.14.0-linux-x64/python_files/interpreterInfo.py'
}
2024-09-10 13:45:49.203 [info] Environments refresh finished (event): 4957 milliseconds
2024-09-10 13:45:49.208 [info] Environments refresh finished (event): 3480 milliseconds
2024-09-10 13:45:49.282 [info] Environment refresh took 5065 milliseconds
2024-09-10 13:45:49.282 [info] Environment refresh took 3566 milliseconds
2024-09-10 13:45:49.363 [info] > pyenv which python
2024-09-10 13:45:49.363 [info] cwd: .
2024-09-10 13:45:52.305 [warning] could not find a pixi interpreter for the interpreter at C:\Users\danie\AppData\Local\Microsoft\WindowsApps\python3.11.exe
2024-09-10 13:45:56.388 [warning] could not find a pixi interpreter for the interpreter at C:\Users\danie\AppData\Local\Microsoft\WindowsApps\python3.11.exe
2024-09-10 13:45:56.477 [info] > C:\Users\danie\AppData\Local\Microsoft\WindowsApps\python3.11.exe -c "import sys;print(sys.executable)"
2024-09-10 13:45:56.612 [error] [Error: Command failed: C:\Users\danie\AppData\Local\Microsoft\WindowsApps\python3.11.exe -c "import sys;print(sys.executable)"
/bin/sh: line 1: C:UsersdanieAppDataLocalMicrosoftWindowsAppspython3.11.exe: command not found

	at genericNodeError (node:internal/errors:984:15)
	at wrappedFn (node:internal/errors:538:14)
	at ChildProcess.exithandler (node:child_process:422:12)
	at ChildProcess.emit (node:events:531:35)
	at maybeClose (node:internal/child_process:1105:16)
	at Socket.<anonymous> (node:internal/child_process:457:11)
	at Socket.emit (node:events:519:28)
	at Pipe.<anonymous> (node:net:338:12)] {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'C:\\Users\\danie\\AppData\\Local\\Microsoft\\WindowsApps\\python3.11.exe -c "import sys;print(sys.executable)"'
}
2024-09-10 13:45:56.748 [info] > pyenv which python
2024-09-10 13:45:56.748 [info] cwd: .
2024-09-10 13:45:56.772 [warning] could not find a pixi interpreter for the interpreter at C:\Users\danie\AppData\Local\Microsoft\WindowsApps\python3.11.exe
2024-09-10 13:45:57.479 [warning] could not find a pixi interpreter for the interpreter at C:\Users\danie\AppData\Local\Microsoft\WindowsApps\python3.11.exe
2024-09-10 13:45:58.439 [warning] could not find a pixi interpreter for the interpreter at C:\Users\danie\AppData\Local\Microsoft\WindowsApps\python3.11.exe
2024-09-10 13:46:01.014 [warning] could not find a pixi interpreter for the interpreter at C:\Users\danie\AppData\Local\Microsoft\WindowsApps\python3.11.exe
2024-09-10 13:49:49.988 [info] Starting Pylance language server.
2024-09-10 13:49:50.218 [warning] could not find a pixi interpreter for the interpreter at C:\Users\danie\AppData\Local\Microsoft\WindowsApps\python3.11.exe
2024-09-10 13:49:50.259 [warning] could not find a pixi interpreter for the interpreter at C:\Users\danie\AppData\Local\Microsoft\WindowsApps\python3.11.exe
2024-09-10 13:49:50.529 [warning] could not find a pixi interpreter for the interpreter at C:\Users\danie\AppData\Local\Microsoft\WindowsApps\python3.11.exe
2024-09-10 13:49:50.606 [warning] could not find a pixi interpreter for the interpreter at C:\Users\danie\AppData\Local\Microsoft\WindowsApps\python3.11.exe
